# This sends a single instance of com.vida.test/simple_event, following the snowplow api format
# It was generated by using the snowplow-test.py, and capturing the POST data parameters from the
# ngrok tunnel introspection (https://ngrok.com/docs#inspect-requests)
curl --request POST \
  --url https://XXX.ngrok.io/snowplow/com.snowplowanalytics.snowplow/tp2 \
  --header 'content-type: application/json' \
  --data '{
    "schema": "iglu:com.snowplowanalytics.snowplow/payload_data/jsonschema/1-0-4",
    "data": [
        {
            "e": "ue",
            "ue_px": "eyJzY2hlbWEiOiAiaWdsdTpjb20uc25vd3Bsb3dhbmFseXRpY3Muc25vd3Bsb3cvdW5zdHJ1Y3RfZXZlbnQvanNvbnNjaGVtYS8xLTAtMCIsICJkYXRhIjogeyJzY2hlbWEiOiAiaWdsdTpjb20udmlkYS50ZXN0L3NpbXBsZV9ldmVudC9qc29uc2NoZW1hLzEtMC0wIiwgImRhdGEiOiB7ImxpbmtfaWQiOiAibXktdGVzdC1saW5rIn19fQ==",
            "eid": "e7fb3cec-34eb-42d5-b2f7-18cc17416625",
            "dtm": "1621293932457",
            "tv": "curl",
            "aid": "docker-local-dev-test",
            "p": "pc",
            "stm": "1621293932000"
        }
    ]
}'
